---

username: 'vmcp'

downloads: ~/.ansible-downloads/

# packages added: bash-completion, certbot, dnsmasq, docker-compose, kubernetes-cli, links, postgresql, yarn 
default_homebrew_installed_packages:
  - awscli
  - azure-cli
  - bash-completion
  - certbot
  - curl
  - dfu-util
  - dnsmasq
  - docker-compose
  - ffmpeg
  - git
  - gnupg
  - gnu-tar
  - go
  - hub
  - jq
  - kubernetes-cli
# - lastpass-cli
  - links
  - mtr
  - nmap
  - node
  - openconnect
  - postgresql
  - pyenv
  - pyenv-virtualenv
  - python
  - python@2
  - terraform
  - tmux
  - tree
  - vim
  - watch
  - wget
  - yarn
  - youtube-dl
  - zsh
  - zsh-syntax-highlighting

homebrew_taps:
  - homebrew/core
  - homebrew/cask

# Additional cask apps to install:  1password, alfred, anyconnect, postman, sonos, virtualbox
homebrew_cask_appdir: /Applications
default_homebrew_cask_apps:
  - 1password
  - appcleaner
  - bettertouchtool
  - docker
#  - dropbox
  - firefox
  - homebrew/cask-drivers/logitech-options
  - homebrew/cask-fonts/font-sourcecodepro-nerd-font
#  - gitkraken
  - google-chrome
  - google-cloud-sdk
  - gpg-suite
  - insomnia
  - iterm2
  - istat-menus
  - malwarebytes
  - microsoft-azure-storage-explorer
  - microsoft-teams
  - postman
  - slack
  - skype
  - skype-for-business
  - spotify
#  - synology-surveillance-station-client
  - tor-browser
# - twitch
  - vagrant
  - vagrant-vmware-utility
  - virtualbox
  - visual-studio-code
  - vlc
  - vmware-fusion
  - vmware-horizon-client
  - wavebox
  - zoomus
  - zoomus-outlook-plugin

# See `geerlingguy.mas` role documentation for usage instructions.
# mas_installed_apps:
#  - { id: 1295203466, name: "Microsoft Remote Desktop" }
#mas_email: ""
#mas_password: ""

#dev_symlinks:
#  - { src: "{{ ansible_user_dir }}/Dropbox/Development/bin",
#      dest: "{{ ansible_user_dir }}/Development/bin"
#    }
#  - { src: "{{ ansible_user_dir }}/Dropbox/Development/gitlab.home.ioports.net",
#      dest: "{{ ansible_user_dir }}/Development/gitlab.home.ioports.net"
#    }
#  - { src: "{{ ansible_user_dir }}/Dropbox/Development/github.emcrubicon.com",
#      dest: "{{ ansible_user_dir }}/Development/github.emcrubicon.com"
#    }
#  - { src: "{{ ansible_user_dir }}/Dropbox/Development/github.com",
#      dest: "{{ ansible_user_dir }}/Development/github.com"
#    }
#  - { src: "{{ ansible_user_dir }}/Dropbox/Development/scratch",
#      dest: "{{ ansible_user_dir }}/Development/scratch"
#    }

osx_script: "~/.osx --no-restart"


gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
